source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'SoulClash' do
    #
    # Samples
    #
    # pod 'AFNetworking', :path => '~/Documents/AFNetworking'
    # pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git'
    # pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :branch => 'dev'
    # pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :tag => '0.7.0'
    # pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :commit => '082f8319af'
    #

    #
    # Opensource projects support CocoaPods directly.
    #
    pod 'PLMediaStreamingKit'
    pod 'AFNetworking',             '~> 3.1.0'
    pod 'CocoaLumberjack',          '~> 3.2.0'
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'PLPlayerKit'
    
    
end
